log_dir: "Checkpoint"
save_freq: 10
device: "cuda"
epochs: 200
batch_size: 256
pretrained_model: ""
train_data: "Data/train_list.txt"
val_data: "Data/val_list.txt"

preprocess_parasm:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300
  mel_params:
    n_mels: 512 #

model_params:
   input_dim: 512 #
   hidden_dim: 256
   n_token: 80
   token_embedding_dim: 256

dataset_params :

optimizer_params:
  lr: 0.0005
